---

apt__package_map:
  'Debian':
    'Ubuntu':
      '16':
        - apt-transport-https
        - apt-utils
        - ca-certificates
        - curl
        - gnupg-agent
        - python-apt
        - software-properties-common
      '18':
        - apt-transport-https
        - apt-utils
        - ca-certificates
        - curl
        - gnupg-agent
        - python-apt
        - software-properties-common
      '20':
        - apt-transport-https
        - apt-utils
        - ca-certificates
        - curl
        - gnupg-agent
        - python3-apt
        - software-properties-common
      '22':
        - apt-transport-https
        - apt-utils
        - ca-certificates
        - curl
        - gnupg-agent
        - python3-apt
        - software-properties-common
