= Concepts

To start using *Axion* you need to create a radar.

To do so:

. Go to *Axion* home page and click *Create*.
. Select the radar type in the corresponding field, for example _Technology radar_.
. Click the button *Add radar*.

The *Axion* will generate and display a radar.

To add technology blips to your radar:

. Navigate to the radar settings.
. Select Technology blips in the menu.
. It will open a list of all blips.
. Click on the *Add a new technology blip*.
. Fill out the form that opens and click on the *Add technology blip* button.

It will add a line with to the selected blip configuration and put it on the created radar.

== Radar configuration

Use *Settings* to customize your radar. Available sections:

* Tenants  
* Technologies
* Radars
* Rings
* Segments 
* Technology blips 

Every section is presented with a table of entities, filter and buttons.

Buttons:

* *Add* -- create a new entity
* *Edit* –- change the existing entity
* *Show* -- display entity information
* *Delete* -- delete the corresponding entity