---
galaxy_info:
  author: developers
  description: workstation
  company: a5lab
  license: license MIT
  min_ansible_version: 1.2
  platforms:
    - name: CentOS
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: RedHat
      versions:
        - all
    - name: Ubuntu
      versions:
        - all

dependencies:
  - role: yum
    when: ansible_os_family == 'RedHat'
  - role: apt
    when: ansible_os_family == 'Debian'
