---

- name: install nodejs repository
  shell: "{{ item }}"
  with_items:
    - "{{ js_env__repo_map[ansible_os_family] }}"

- name: install js packages
  package:
    name: "{{ js_env__package_map[ansible_os_family][ansible_distribution][ansible_distribution_major_version] }}"
    state: present

- name: install npm packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  with_items:
    - "{{ js_env__npm_map }}"
