---

- name: install apache packages
  package:
    name: "{{ apache__package_map[ansible_os_family] }}"
    state: present

- name: enable apache modules for debian
  shell: "a2enmod {{ item }}"
  with_items: "{{ apache__module_map }}"
  when:
    - ansible_os_family == 'Debian'

- name: systemctl enable apache
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ apache__service_map[ansible_os_family] }}"
  notify:
    - restart apache

- name: create certbot hooks files for apache
  template:
    src: "etc/letsencrypt/renewal-hooks/deploy/{{ item }}.sh.j2"
    dest: "/etc/letsencrypt/renewal-hooks/deploy/{{ item }}.sh"
    owner: "root"
    group: "root"
    mode: "0770"
  with_items:
    - apache

- name: execute certbot hooks after install for apache
  shell: "/etc/letsencrypt/renewal-hooks/deploy/{{ item }}.sh"
  environment:
    RENEWED_DOMAINS: "{{ inventory_hostname }}"
    RENEWED_LINEAGE: "/etc/letsencrypt/live/{{ inventory_hostname }}"
  args:
    executable: /bin/bash
  with_items:
    - apache

