logging:
  level:
    root: info
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:axion;MODE=PostgreSQL
    username: axion
    password: secret
  h2:
    console:
      enabled: true
  messages:
    use-code-as-default-message: false
  thymeleaf:
    cache: false
  resources:
    cache-period: 0
  jpa:
    show-sql: true
