logging:
  level:
    root: info

spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  datasource:
    url: jdbc:h2:mem:tabr;MODE=PostgreSQL
    username: tabr
    password: secret
  h2:
    console:
      enabled: true
  messages:
    use-code-as-default-message: false
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
    cache-period: 0
  jpa:
    show-sql: true