server:
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript
    min-response-size: 512
  http2:
    enabled: true
  error:
    whitelabel:
      enabled: true

spring:
  application:
    name: TABR
  jmx:
    enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/tabr
    username: tabr
    password: tabr
    hikari:
      poolName: tabr-pool
      auto-commit: false
      minimum-idle: 20
      maximum-pool-size: 100
      max-lifetime: 300000
      validation-timeout: 500
      idle-timeout: 60000
      leak-detection-threshold: 80000
      connection-timeout: 20000
      initialization-fail-timeout: 1
      isolate-internal-queries: false
      allow-pool-suspension: false
      login-timeout: 10000
  transaction:
    rollback-on-commit-failure: true
    default-timeout: 30s
  liquibase:
    change-log: db/changelog/changelog-master.xml
  thymeleaf:
    cache: true
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  mvc:
    servlet:
      load-on-startup: 1
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        hql.bulk_id_strategy: org.hibernate.hql.spi.id.inline.InlineIdsInClauseBulkIdStrategy
        order_updates: true
        order_inserts: true
        default_batch_fetch_size: 1000
        enable_lazy_load_no_trans: false
        batch_fetch_style: dynamic
        jdbc:
          time_zone: UTC
          lob.non_contextual_creation: true
          batch_size: 200
          fetch_size: 300
          batch_versioned_data: true
        id.new_generator_mappings: true
        generate_statistics: false
    hibernate:
      ddl-auto: validate
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 120
          must-revalidate: true



