---

- name: reload apache
  service:
    name: "{{ app__apache_service_map[ansible_os_family] }}"
    state: reloaded

- name: restart apache
  service:
    name: "{{ apache__service_map[ansible_os_family] }}"
    state: restarted
