# This configuration is intended for development purpose
version: '3.8'
services:
  tabr-postgresql:
    image: postgres:14.6
    environment:
      - POSTGRES_USER=tabr
      - POSTGRES_PASSWORD=tabr
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
