# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  axion-sonar:
    image: sonarqube:latest
    # Authentication is turned off for out of the box experience while trying out SonarQube
    environment:
      - sonar.forceAuthentication=false
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9000:9000
