= Technical and business radar
:navtitle: Technical and business radar

Technical and business radar (*tabr*) is irreplaceable when working on many products, and many tools, frameworks and programming languages are used for development. *tabr* creates a complete map of the technology stack, down to the designation of the selected landscape, which makes it indispensable for developers, architects and managers. 

See how to xref:installation:pages/overview.adoc[install] and start xref:installation:pages/overview.adoc[using] *tabr*.

We have also gathered some of our xref:best_practices:pages/overview.adoc[best practices] for better understanding on how to use




//// 
This page is sourced from the AsciiDoc file named [.path]_index.adoc_ that is located at [.path]_demo-component-b/docs/modules/ROOT/pages_.

=== Why is this the home page of Component B?

This page is automatically used as the start page of Component B because it is stored in the ROOT module and named [.path]_index.adoc_.

=== Why is this the home page of the Antora Demo site?

This page is used as the home page for the Antora Demo because it is assigned as the site `start_page` in the Demo site's playbook file [.path]_site.yml_.

== Cross reference syntax to target this page

To create a cross reference *to this page from another page in the ROOT module of Component B*, the xref syntax would be `\xref:index.adoc[]`.

To create a cross reference *to this page from a page in Module One of Component B*, the xref syntax would be `\xref:ROOT:index.adoc[]`.

=== Always target the latest version of this page

To create a cross reference *to the latest version of this page from a page in Component A*, the xref syntax would be `\xref:component-b::index.adoc[]`.

=== Target a specific version of this page

To create a cross reference *to version 1.0 of this page from a page in Component A*, the xref syntax would be `\xref:1.0@component-b::index.adoc[]`.
//// 