---

openjre__brew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
openjre__brew_bin_path: "{{ openjre__brew_prefix }}/bin"

# Default package map
openjre__package_map:
  'Darwin':
    - openjre
  'RedHat':
    - java-11-openjre
  'Debian':
    - openjdk-17-jre

