---

# Domains for certbot
certbot__domains: []

# Cert type: letsencrypt or letsselfsign
certbot__cert_type: "letsencrypt"

# Domains for certbot: apache or nginx
certbot__web_server: "apache"

# Hostmaster mail
certbot__hostmaster_mail: "hostmaster@a5lab.com"

certbot__apache_package_map:
  'RedHat':
    - httpd
    - mod_ssl
    - httpd-tools
  'Debian':
    - apache2
    - apache2-utils

certbot__nginx_package_map:
  'RedHat':
    - nginx
  'Debian':
    - nginx

certbot__package_map:
  'RedHat':
    'CentOS':
      '7':
        - certbot
        - curl
        - openssl
        - python2-certbot-apache
      '8':
        - curl
        - openssl
  'Debian':
    'Ubuntu':
      '16':
        - certbot
        - curl
        - openssl
        - python-certbot-apache
      '18':
        - certbot
        - curl
        - openssl
        - python-certbot-apache
      '20':
        - certbot
        - curl
        - openssl
        - python3-certbot-apache
      '22':
        - certbot
        - curl
        - openssl
        - python3-certbot-apache

certbot__binary_map:
  'RedHat':
    'CentOS':
      '7': certbot
      '8': /usr/local/bin/certbot-auto
  'Debian':
    'Ubuntu':
      '16': certbot
      '18': certbot
      '20': certbot
      '22': certbot
