---

# The 'service' key is for firewalld, the 'port' key is for ufw
firewall_default_services:
  - { service: 'ssh', port: 'ssh', rule: 'allow' }
  - { direction: 'outgoing', policy: 'allow' }
  - { direction: 'incoming', policy: 'deny' }

firewall_allow_services:
  - { service: 'http', port: 'http', rule: 'allow' }
  - { service: 'https', port: 'https', rule: 'allow' }
  - { service: 'postgresql', port: 'postgresql', rule: 'allow' }

firewall_allow_ports: {}

firewall_disable: false
