---

- name: create directories for application
  file:
    path: "{{ item }}"
    owner: "{{ app__user }}"
    group: "{{ app__group }}"
    state: directory
    mode: "0755"
  with_items:
    - "{{ app__shared_path }}"
    - "{{ app__shared_path }}/certs"

- name: create certbot hooks files for app
  template:
    src: "etc/letsencrypt/renewal-hooks/deploy/{{ item }}.sh.j2"
    dest: "/etc/letsencrypt/renewal-hooks/deploy/{{ item }}.sh"
    owner: "root"
    group: "root"
    mode: "0770"
  with_items:
    - puma

- name: execute certbot hooks after install for app
  shell: "/etc/letsencrypt/renewal-hooks/deploy/{{ item }}.sh"
  environment:
    RENEWED_DOMAINS: "{{ app__domain }}"
    RENEWED_LINEAGE: "/etc/letsencrypt/live/{{ app__domain }}"
  args:
    executable: /bin/bash
  with_items:
    - puma
