---

- name: install apache packages
  package:
    name: logrotate
    state: present

- name: configure logrotate
  template:
    src: "etc/logrotate.d/a5lab.j2"
    dest: '/etc/logrotate.d/a5lab'
    owner: 'root'
    group: 'root'
    mode: '0644'
