---

- name: install the systemd unit file
  template:
    src: 'etc/systemd/system/{{ item }}.service.j2'
    dest: '/etc/systemd/system/{{ item }}.service'
    owner: 'root'
    group: 'root'
    mode: '0644'
  with_items: "{{ app__web_servers }}"
  when:
    - ansible_service_mgr|d()
    - ansible_service_mgr in [ "systemd" ]

- name: register autostart service systemd
  service:
    name: '{{ item }}'
    enabled: 'yes'
  with_items: "{{ app__web_servers }}"
  when:
    - ansible_service_mgr|d()
    - ansible_service_mgr in [ "systemd" ]

- name: force systemd to reread configs
  systemd: daemon_reload=yes

