---

# Logging configuration to avoid output sensitive information.
app__no_log: false

#
# Database section
# App adapter can be: postgresql, mysql2, sqlite
#
app__db_adapter: "postgresql"
app__db_name: "tabr"
app__db_user: "tabr"
app__db_password: '{{ lookup("env", ci_environment_name + "_database_password") or "secret"}}'
app__db_host: "{{ hostvars[groups.demo_server.0].ansible_host }}"

#
# SMTP section
#
app__smtp_address: "mail.a5lab.com"
app__smtp_domain: "a5lab.com"
app__smtp_port: "25"
app__smtp_user_name: "support@a5lab.com"
app__smtp_user_password: '{{ lookup("env", ci_environment_name + "_support_mail_password") or "secret" }}'

#
# Settings section
#
app__domain: "{{ inventory_hostname }}"
app__protocol: 'https'

#
# Deploy section
#
app__user: "tabr"
app__group: "tabr"
app__root_path: '/home/{{ app__user }}'
app__current_path: "{{ app__root_path }}/current"
app__release_path: "{{ app__root_path }}/releases/{{ ansible_date_time.iso8601_basic_short }}"
app__keep_releases: 5
app__web_servers:
  - tabr

#
# Service configuration
#
app__apache_service_map:
  'RedHat': "httpd"
  'Debian': "apache2"

app__apache_conf_map:
  'RedHat': "httpd/conf.d"
  'Debian': "apache2/sites-available"

app__apache_templates:
  - robots.txt
