---

# `item.state`, `item.architecture`, `item.distribution` and `item.distribution_release` need to be checked here.
# Ref: https://github.com/debops/ansible-apt/pull/76#pullrequestreview-2529842
- name: configure custom apt keys
  become: yes
  apt_key:
    data:      '{{ item.data      | d(omit) }}'
    file:      '{{ item.file      | d(omit) }}'
    id:        '{{ item.id        | d(omit) }}'
    keyring:   '{{ item.keyring   | d(omit) }}'
    keyserver: '{{ item.keyserver | d(omit) }}'
    url:       '{{ item.url       | d(omit) }}'
    state:     '{{ item.state     | d("present"
                                      if (item.architecture|d(apt__architecture) == apt__architecture and
                                          item.distribution|d(apt__distribution) == apt__distribution and
                                          item.distribution_release|d(apt__distribution_release) == apt__distribution_release)
                                      else omit) }}'
  with_flattened:
    - '{{ apt__keys }}'
    - '{{ apt__group_keys }}'
    - '{{ apt__host_keys }}'
  when: (apt__enabled|bool and (item.url|d() or item.data|d() or item.id|d() or item.file|d()) and
         (item.state|d("present") == 'present' and
          (item.architecture|d(apt__architecture) == apt__architecture and
           item.distribution|d(apt__distribution) == apt__distribution and
           item.distribution_release|d(apt__distribution_release) == apt__distribution_release)))

- name: configure custom apt repositories
  become: yes
  apt_repository:
    update_cache: False
    repo:     '{{ item.repo }}'
    mode:     '{{ item.mode     | d(omit) }}'
    filename: '{{ item.filename | d(omit) }}'
    state:    '{{ item.state    | d("present"
                                    if (item.architecture|d(apt__architecture) == apt__architecture and
                                        item.distribution|d(apt__distribution) == apt__distribution and
                                        item.distribution_release|d(apt__distribution_release) == apt__distribution_release)
                                    else "absent") }}'
  with_flattened:
    - '{{ apt__repositories }}'
    - '{{ apt__group_repositories }}'
    - '{{ apt__host_repositories }}'
  register: apt__register_repositories
  when: (apt__enabled|bool and item.repo|d())

- name: install packages to update apt cache
  become: yes
  apt:
    name: "{{ apt__package_map[ansible_os_family][ansible_distribution][ansible_distribution_major_version] }}"
    state: 'present'
    install_recommends: False
  when: apt__enabled|bool

- name: update apt cache
  become: yes
  apt:
    update_cache: True
  when: apt__enabled|bool
