---

- name: stat public path
  stat:
    path: "{{ maintenance__path }}"
  register: public_path

- name: turn on maintenance
  file:
    path: "{{ maintenance__path }}/{{ maintenance__file }}"
    owner: "{{ maintenance__user }}"
    group: "{{ maintenance__group }}"
    state: touch
  when: public_path.stat.exists
