#
# Build and test plugin
#
name: Build and test plugin

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v3
    - name: Install JDK
      uses: ./.github/actions/jdk
    - name: Build package
      run: mvn package
