#
# Deploy application
#
name: Deploy application

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install JDK
        uses: ./.github/actions/jdk
      - name: Install NodeJS
        uses: ./.github/actions/nodejs
      - name: Build package
        shell: bash
        run: mvn package
      - name: Deploy package
        shell: bash
        run: echo deploy
      - name: Show git info
        shell: bash
        run: git branch && git show
