#
# Build and release application
#
name: Release application

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'liberica'
          cache: maven
      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm packages
        shell: bash
        run: npm install uglifycss uglify-js -g
      - name: Verify package
        shell: bash
        run: mvn verify
      - name: Create archive
        shell: bash
        run: cd ./target && tar -zcvf tabr.tar.gz tabr*.jar
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          files: ./target/tabr.tar.gz
          draft: true
          prerelease: false
