#
# Build and release application
#
name: Release application

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
