#
# Build and release application
#
name: Release application

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version'
        required: true
        default: '1.0.0'
        type: string
      development_version:
        description: 'Development version'
        required: true
        default: '1.0.1-SNAPSHOT'
        type: string
      tag:
        description: 'Tag'
        required: true
        default: 'ssp-1.0.0'
        type: string
      email:
        description: 'Email for git'
        required: true
        default: 'arufanov@gmail.com'
        type: string
      username:
        description: 'Username for git'
        required: true
        default: 'Artem.Rufanov'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install JDK
        uses: ./.github/actions/jdk
      - name: Install NodeJS
        uses: ./.github/actions/nodejs
      - name: Checkout sources
        uses: actions/checkout@v3
