#
# Build and release application
#
name: Release application

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag'
        required: true
        default: '1.0.0'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}
      - name: Install JDK
        uses: ./.github/actions/jdk
      - name: Install NodeJS
        uses: ./.github/actions/nodejs
      - name: Build package
        shell: bash
        run: mvn package
      - name: Release package
        shell: bash
        run: echo release
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/asset.zip
          asset_name: asset.zip
          asset_content_type: application/zip
